### PR TITLE
Update to LIFX Libs

### PR DESCRIPTION
**Pull request by Cakey123445**
I've pulled in previous pull requests, reformatted the code, increased the debugging levels and more importantly put a fix in place to stop the libraries crashing when an protocol 5 is received, this is now correctly (or not) mapped to UDP.

Debugging is turned up to max, so there is a lot of noise, you can turn it down/off in LFXLog.java.

There are plenty of errors coming from the unimplemented TCP, also I can still get the lib in a state where it starts leaving lots of threads running but not sure what the trigger is yet.

Lots of work still to be done but with this version I can at least control a bulb.

### CODE REVIEW

**Comment by chendo** [comment]
Thanks for the PR! However, would it be possible to undo the formatting changes in this PR? It's hard to review due to the massive diff.

**Comment by Cakey123445** [comment]
As you can guess there are quite a few hours work in the reformatting so I'm not keen/willing to back those out, however key changes over the other PRs (which have been merged) are to the following files:

library/src/lifx/java/android/entities/internal/structle/LxProtocolDevice.java - Fixes crash by mapping protocol==5 to UDP rather than returning a null from the mapping which then crashes the app/lib.

library/src/lifx/java/android/util/LFXLog.java - Modified logging

All other changes are removal of hard tabs, reformatting and adding/changing the logging to try and help to debug/understand the library.

**Comment by smarthall** [comment]
I've reviewed these changes and confirmed that the app no longer crashes, and can now see Firmware 2.0 bulbs.

I'm going to go ahead and merge them.

**Comment by smarthall** [comment]
I just wanted to say thanks to @Cakey123445, @Connor-Vickers and @ekux44 for doing this work. If any of you would like to maintain this library going forward let me know and I'll see what we can do.

Remember if you ever need developer support you can get in touch with us at https://community.lifx.com/ or by emailing us at developers@lifx.co.

**Comment by ekux44** [comment]
Thanks @Cakey123445 for fixing the crashes on Firmware 2.0 bulbs! I've gotten so many angry emails from LampShade.io users that own LIFX devices, but I hadn't had the time to look into it.

Glad to see LIFX people finally checking in on the SDK. That said, is this SDK sustainable as a community project? It's got so many bugs (not to mention new bugs as bulb firmware changes), that I've been wondering if I should just rewrite my app to use the LIFX Web API (a nontrivial switch, especially if users have to reauthenticate).

**Pull request merged**
